### PR TITLE
Add message type parameter to outbound requests for sms transport

### PR DESCRIPTION
**Pull request by justinvdm**
This parameter isn't something we need, and according to the docs is optional, but from testing it seemed necessary for it to be provided.

### CODE REVIEW

**Comment by justinvdm** [comment]
Ready for review. Depends on #6 since tests added in #6 needed updating.

**Comment by hodgestar** [comment]
Could we leave a comment saying what `message_type` `1` means? Otherwise looks good.

**Comment by justinvdm** [comment]
@hodgestar not too sure what `message_type` is tbh, all I know is they are expecting it to be `'1'`.

All the docs say is

```
Flag indicating normal text message
```

and

```
0 or 1  Note: 1=flash, 0=text (This is optional, the default is 0 i.e text)
```

**Comment by hodgestar** [comment]
@justinvdm Maybe `flag indicating normal text message` is enough?

**Comment by justinvdm** [comment]
@hodgestar I can add that, but I don't even know what they mean by that. They are also expecting a value of `1` even though `1` appears to  not mean normal text message (`0` indicates normal text message, if I'm understanding correctly). I'll try document it.

**Comment by justinvdm** [comment]
Comment added, ready for re-review.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
